version: "3.9"
services:
  app:
    image: registry.s-p-it.de/darkmatus/shelly:shelly
    volumes:
      - .:/opt/app/api
    ports:
      - "8021:80"
    environment:
      - APP_NAME=shelly
      - ENVIRONMENT=test